# Generated by Django 4.0.4 on 2022-05-05 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_blog_delete_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
